### ISSUE TITLE
Design de la zone heures de jeu

### ISSUE THREAD

**Issue by bvergnaud** [Eldii/evilducks#1]
Il y a quelques détails perfectible point de vue design sur cette zone:

- Je pense qu'on devrait pouvoir aligner les 5 compteurs en une ligne si on garde ce format, en plein écran, sur un écran 1080p.

- Il y a aussi un espace trop petit juste sous le dernier compteur et la fin de la section. C'est pas très esthétique. Là :

![kaermorhen-2017-01-02-234301](https://cloud.githubusercontent.com/assets/9599845/21597147/d1e5b3fe-d145-11e6-918e-549c09f83d88.png)

- Et il y a quelques améliorations à faire sur le responsive =P Exemples:

![kaermorhen-2017-01-02-234042](https://cloud.githubusercontent.com/assets/9599845/21597096/fe1a5a20-d144-11e6-8c2c-52fab3d14434.png)
![kaermorhen-2017-01-02-234109](https://cloud.githubusercontent.com/assets/9599845/21597097/fe209fd4-d144-11e6-8cb2-232c217ed35c.png)

**Comment by Eldii** [comment]
Fixed
