### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheMightyAhix** [Eldii/evilducks#12]
- [ ] Eng pls. We don't get monkey language.
- [ ] Users should be able to select demos by clicking their respective rows, not only the check thingy
- [ ] Users should be able to retrieve download links to share demopacks directly to other users without having theme to go through the process of selecting the aforementioned demos
- [ ] Sort demos by date in descending order so that the last ones are on top. (Or sort them alphabetically in descending order [but if I mess us the name of the demo, all the sorting is screwed and i'll blame YOU, damn techies...]) 
- [ ] Add a '?' next to the downloadspeed box explaining what checking/unchecking the box does.
- [x] ~~I get that baguettes are late to the High Download speed party but demo compression should not be enable by default (It's slower to compress then DL for me than DLing right away).~~
- [x] ~~Compression could be default when downloading a very large ammount of data (I leave to you, techies, the choice of this ammount)~~

**Comment by bvergnaud** [comment]
"I get that baguettes are late to the High Download speed party but demo compression should not be enable by default (It's slower to compress then DL for me than DLing right away)."
"Compression could be default when downloading a very large ammount of data (I leave to you, techies, the choice of this ammount)"

You're the only one in the team to have optic fiber yet. In all other case, this results in equal or shorter download times. Plus it gives you that feel good vibe by reminding you that you have a GREAT bandwidth.

Won't change.

**Comment by TheMightyAhix** [comment]
fascist.

**Comment by bvergnaud** [comment]
Find us an efficient method to know the user's bandwidth and we can get rid of the box entirely. Pull request are welcome.

**Comment by Eldii** [comment]
Done. I hope all is good for u ma frend
