### ISSUE TITLE
Pages Démos Broken

### ISSUE THREAD

**Issue by bvergnaud** [Eldii/evilducks#8]
AH! Bah c'est bien du travail de singe ça...

- Le fichier download_demo.zip n'est pas supprimé après le transfert. Espace disque utilisé pour rien.
- Le tableau déborde de l'écran, pas scrollable ni rien.
- Le bouton "télécharger" reste en plein milieu du tableau quand il grandit.

Voilà =D

**Comment by Eldii** [comment]
Fixed
